frr defaults traditional
hostname r4
!
interface lo
 ip address 4.4.4.4/32
!
interface eth1
 ip address 10.0.34.2/30
!
interface eth2
 ip address 10.0.41.1/30
!
router ospf
 network 4.4.4.4/32 area 0
 network 10.0.34.0/30 area 0
 network 10.0.41.0/30 area 0
!
