frr defaults traditional
hostname r4
!
interface lo
 ip address 4.4.4.4/32
 ip ospf area 0
!
interface eth1
 ip address 10.0.34.2/30
 ip ospf area 0
!
interface eth2
 ip address 10.0.41.1/30
 ip ospf area 0
!
router ospf
 ospf router-id 4.4.4.4
!
