frr defaults traditional
hostname r3
!
interface lo
 ip address 3.3.3.3/32
 ip ospf area 0
!
interface eth1
 ip address 10.0.23.2/30
 ip ospf area 0
!
interface eth2
 ip address 10.0.34.1/30
 ip ospf area 0
!
router ospf
 ospf router-id 3.3.3.3
!
