frr defaults traditional
hostname r3
!
interface lo
 ip address 3.3.3.3/32
!
interface eth1
 ip address 10.0.23.2/30
!
interface eth2
 ip address 10.0.34.1/30
!
router ospf
 network 3.3.3.3/32 area 0
 network 10.0.23.0/30 area 0
 network 10.0.34.0/30 area 0
!
