frr defaults traditional
hostname r1
!
interface lo
 ip address 1.1.1.1/32
 ip ospf area 0
!
interface eth1
 ip address 10.0.12.1/30
 ip ospf area 0
!
interface eth2
 ip address 10.0.41.2/30
 ip ospf area 0
!
router ospf
 ospf router-id 1.1.1.1
!
