frr defaults traditional
hostname r1
!
interface lo
 ip address 1.1.1.1/32
 ip ospf area 0
!
interface eth1
 ip address 10.0.12.1/30
 ip ospf area 0
!
interface eth2
 ip address 10.0.41.2/30
 ip ospf area 0
!
router ospf
 ospf router-id 1.1.1.1
!
!
ip route 192.168.100.0/24 Null0
!
router bgp 65000
 neighbor 2.2.2.2 remote-as 65000
 neighbor 2.2.2.2 update-source lo
 neighbor 3.3.3.3 remote-as 65000
 neighbor 3.3.3.3 update-source lo
 neighbor 4.4.4.4 remote-as 65000
 neighbor 4.4.4.4 update-source lo
 address-family ipv4 unicast
  network 192.168.100.0/24
 exit-address-family
!
